export const UPDATE_COMMENT = "UPDATE_COMMENT"
export const SET_TOKEN = "SET_TOKEN"

export const ME_REQUEST = "ME_REQUEST"
export const ME_REQUEST_SUCCESS = "ME_REQUEST_SUCCESS"
export const ME_REQUEST_ERROR = "ME_REQUEST_ERROR"

export const POSTS_REQUEST = "POSTS_REQUEST"
export const POSTS_REQUEST_SUCCESS = "POSTS_REQUEST_SUCCESS"
export const POSTS_REQUEST_ERROR = "POSTS_REQUEST_ERROR"